# Dependencies
gems:             [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            "Pete Peterson"
tagline:          "Pete Peterson Music"
description:      ""
url:              https://petepetersonmusic.com
baseurl:          https://petepetersonmusic.com/
permalink:        /:title

author:
  name:           "Pete Peterson"
  url:            https://twitter.com/petepm

paginate:         5

github:
  repo:           https://github.com/petepm/petepm.github.io

twitter_username: petepm
github_username: petepm
instagram_username: petep.me
facebook_username: petepetersonmusic
youtube_username: petepetersonmusic
soundcloud_username: petepetersonmusic
bandcamp_username: petepeterson
