# Dependencies
plugins:
  - jekyll-paginate

# Permalinks
permalink: pretty

# Setup
title: "Pete Peterson"
tagline: "Pete Peterson Music"
description: ""
url: https://petepetersonmusic.com
baseurl: ""

author:
  name: "Pete Peterson"
  url: https://petep.me

paginate: 5

github:
  repo: https://github.com/petepm/petepm.github.io

# Social
github_username: petepm
instagram_username: petep.me
facebook_username: petepetersonmusic
youtube_username: petepetersonmusic
soundcloud_username: petepetersonmusic
bandcamp_username: petepeterson
threads_username: petep.me
