# Dependencies
plugins:
  - jekyll-paginate

# Permalinks
permalink: pretty

# Setup
title: "Pete Peterson"
tagline: "Pete Peterson Music"
description: ""
url: https://petepetersonmusic.com
baseurl: ""

author:
  name: "Pete Peterson"
  url: https://petep.me

paginate: 5

github:
  repo: https://github.com/petepm/petepm.github.io

# Social
github_username: petepm
instagram_username: petep.me
facebook_username: petepetersonmusic
youtube_username: petep
soundcloud_username: petepetersonmusic
bandcamp_username: petepeterson
threads_username: petep.me
spotify_url: https://open.spotify.com/artist/1RwqdFQvLZmq7AMsJhTbxL?si=uF297gYLQd-kRCdwkv-w7Q
apple_music_url: https://music.apple.com/us/artist/pete-peterson/20385570
tiktok_username: petep.me
